Создание верстки календаря
Oleg-Pronin/HomeworkCalculator pull request #1
Opened 2021-06-04 15:35 UTC by Oleg-Pronin

2021-06-05 20:57 UTC, DwarfPorter requested changes
И у вас стоит минSDK 29, это не слишком много устройств вы оставили за бортом?

2021-06-05 20:57 UTC, DwarfPorter commented on app/src/main/res/layout/activity_main.xml
> +        android:paddingBottom="10dp"
Ну ладно, на эти параметры готов закрыть глаза, что они не в ресурсах

2021-06-05 20:57 UTC, DwarfPorter commented on app/src/main/res/layout/activity_main.xml
> +        android:text="1000÷10"
Но вот тут, надо строку отправлять в ресурсы.
-1 балл

2021-06-05 20:57 UTC, DwarfPorter commented on app/src/main/res/layout/activity_main.xml
> +        android:text="100"
в ресурсы

2021-06-06 08:07 UTC, Oleg-Pronin commented on app/src/main/res/layout/activity_main.xml
> +        android:text="1000÷10"
Это строка является пример. В дальнейшей реализации значения `android:text="1000÷10"` не будет и добавлять ее в ресурсы нет смысла, т.к. потом это будет лишним мусором. Со снижением оценки не согласен.

2021-06-06 08:09 UTC, Oleg-Pronin commented on app/src/main/res/layout/activity_main.xml
> +        android:text="100"
Это строка является пример. В дальнейшей реализации значения android:text="100" не будет и добавлять ее в ресурсы нет смысла, т.к. потом это будет лишним мусором.

2021-06-07 15:30 UTC, DwarfPorter commented on app/src/main/res/layout/activity_main.xml
> +        android:text="100"
Ok

2021-06-07 15:31 UTC, DwarfPorter approved these changes

2021-06-07 16:01 UTC, merged